CUDA-Image-Encryption: include/io.hpp File Reference
io.hpp File Reference
Functions
static long rwLMParameters (FILE *outfile, const char *file_path, const char *mode, config::lm lm_parameters[], int iteration, int number_of_rounds, long ptr_position)
This header file contains functions for reading and writing parameters.
static long rwLMAParameters (FILE *outfile, const char *file_path, const char *mode, config::lma lma_parameters[], int iteration, int number_of_rounds, long ptr_position)
Read or write Logistic Map Advanced parameters.
static long rwSLMMParameters (FILE *outfile, const char *file_path, const char *mode, config::slmm slmm_parameters[], int iteration, int number_of_rounds, long ptr_position)
Read or write Sine Logistic Modulation Map parameters.
static long rwLASMParameters (FILE *outfile, const char *file_path, const char *mode, config::lasm lasm_parameters[], int iteration, int number_of_rounds, long ptr_position)
Read or write Logistic Adjusted Sine Map parameters.
static long rwLALMParameters (FILE *outfile, const char *file_path, const char *mode, config::lalm lalm_parameters[], int iteration, int number_of_rounds, long ptr_position)
Read or write Logistic Adjusted Logistic Map parameters.
static long rwMTParameters (FILE *outfile, const char *file_path, const char *mode, config::mt mt_parameters[], int iteration, int number_of_rounds, long ptr_position)
Read or write Mersenne Twister seed.
Function Documentation
static long rwLMParameters (FILE * outfile, const char * file_path, const char * mode, config::lm lm_parameters[], int iteration, int number_of_rounds, long ptr_position) inline static
This header file contains functions for reading and writing parameters.
Read or write Logistic Map parameters.
Takes Logistic Map parameters, filepath, iteration and number of rounds as arguments
Offset pointer position by length of previous record
Write LM parameters to file
Update pointer position after writing
Ofsetting pointer position by length of revious record
Read LM parameters from file
Update pointer position after reading
Definition at line 19 of file io.hpp.
References DEBUG_READ_WRITE.
Referenced by pattern::rwMapParameters().
   {
     long pointer_position = ptr_position;
     int fwrite_status = 9,fseek_status = 9,fread_status = 9;
     outfile = fopen(file_path,mode);
     if(outfile == NULL)
     {
       cout<<"\nCould not open "<<file_path<<"\nExiting...";
       exit(0);
     }
     if(strcmp("ab",mode) == 0 || strcmp("wb",mode) == 0)
     {
       if(pointer_position > 0)
       {
         fseek_status = fseek(outfile,(pointer_position + 1),SEEK_SET);
         pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before writing lm_parameters = "<<fseek_status;
         cout<<"\npointer position before writing lm_parameters = "<<pointer_position;
       }
       size_t size = number_of_rounds * sizeof(lm_parameters[0]);
       fwrite_status = fwrite(lm_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfwrite status after writing lm_parameters = "<<fwrite_status;
         cout<<"\npointer position after writing lm_parameters = "<<pointer_position;
       }
     }
     else
     {
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\npointer position before reading lm_parameters = "<<pointer_position;
       }
       if(pointer_position > 0)
       {
         fseek_status = fseek(outfile,(pointer_position),SEEK_SET);
         pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before reading lm_parameters = "<<fseek_status;
         cout<<"\npointer position before writing lm_parameters = "<<pointer_position;
       }
       size_t size = number_of_rounds * sizeof(lm_parameters[0]);
       fread_status = fread(lm_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfread status after reading lm_parameters = "<<fread_status;
         cout<<"\npointer position after reading lm_parameters = "<<pointer_position;
       }
     }
     fclose(outfile);
     return pointer_position;
   }
static long rwLMAParameters (FILE * outfile, const char * file_path, const char * mode, config::lma lma_parameters[], int iteration, int number_of_rounds, long ptr_position) inline static
Read or write Logistic Map Advanced parameters.
Takes Logistic Map Advanced parameters, filepath, iteration and number of rounds as arguments
Offset pointer position by length of previous record
Write LMA parameters to file
Update pointer position after writing
Offset pointer position by length of previous record
Read LMA parameters from file
Update pointer position after reading
Definition at line 117 of file io.hpp.
References DEBUG_READ_WRITE.
Referenced by pattern::rwMapParameters().
   {
     long pointer_position = ptr_position;
     int fwrite_status = 9,fseek_status = 9,fread_status = 9;
     outfile = fopen(file_path,mode);
     if(outfile == NULL)
     {
       cout<<"\nCould not open "<<file_path<<"\nExiting...";
       exit(0);
     }
     if(strcmp("wb",mode) == 0 || strcmp("ab",mode) == 0)
     {
       if(pointer_position > 0)
       {
         fseek_status = fseek(outfile,(pointer_position + 1),SEEK_SET);
         pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before writing lma_parameters = "<<fseek_status;
         cout<<"\npointer position before writing lma_parameters = "<<pointer_position;
       }
       size_t size = sizeof(lma_parameters[0]) * number_of_rounds;
       fwrite_status = fwrite(lma_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfwrite status after writing lma_parameters = "<<fwrite_status;
         cout<<"\npointer position after writing lma_parameters = "<<pointer_position;
       }
     }
     else
     {
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\npointer position before reading lma_parameters = "<<pointer_position;
       }
       if(pointer_position > 0)
       {
         fseek_status = fseek(outfile,(pointer_position),SEEK_SET);
         pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before reading lma_parameters = "<<fseek_status;
         cout<<"\npointer position before reading lma_parameters = "<<pointer_position;
       }
       size_t size = sizeof(lma_parameters[0]) * number_of_rounds;
       fread_status = fread(lma_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfread status after writing lma_parameters = "<<fread_status;
         cout<<"\npointer position after reading lma_parameters = "<<pointer_position;
       }
     }
     fclose(outfile);
     return pointer_position;
   }
static long rwSLMMParameters (FILE * outfile, const char * file_path, const char * mode, config::slmm slmm_parameters[], int iteration, int number_of_rounds, long ptr_position) inline static
Read or write Sine Logistic Modulation Map parameters.
Takes Sine Logistic Modulation Map parameters, filepath, iteration and number of rounds as arguments
Offset pointer position by length of previous record
Write SLMM parameters to file
Update pointer position after writing
Offset pointer position by length of previous record
Read SLMM parameters from file
Update pointer position after reading
Definition at line 214 of file io.hpp.
References DEBUG_READ_WRITE.
Referenced by pattern::rwMapParameters().
   {
     long pointer_position = ptr_position;
     int fwrite_status = 9,fseek_status = 9,fread_status = 9;
     outfile = fopen(file_path,mode);
     if(outfile == NULL)
     {
       cout<<"\nCould not open "<<file_path<<"\nExiting...";
       exit(0);
     }
     if(strcmp("wb",mode) == 0 || strcmp("ab",mode) == 0)
     {
       if(pointer_position > 0)
       {
          fseek_status = fseek(outfile,(pointer_position + 1),SEEK_SET);
          pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before writing slmm_parameters = "<<fseek_status;
         cout<<"\npointer position before writing slmm_parameters = "<<pointer_position;
       }
       size_t size = sizeof(slmm_parameters[0]) * number_of_rounds;
       fwrite_status = fwrite(slmm_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfwrite status after writing slmm_parameters = "<<fwrite_status;
         cout<<"\npointer position after writing slmm_parameters = "<<pointer_position;
       }
     }
     else
     {
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\npointer position before reading slmm_parameters = "<<pointer_position;
       }
       if(pointer_position > 0)
       {
          fseek_status = fseek(outfile,(pointer_position),SEEK_SET);
          pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before reading slmm_parameters = "<<fseek_status;
         cout<<"\npointer position before reading slmm_parameters = "<<pointer_position;
       }
       size_t size = sizeof(slmm_parameters[0]) * number_of_rounds;
       fread_status = fread(slmm_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfread status after reading slmm_parameters = "<<fread_status;
         cout<<"\npointer position after reading slmm_parameters = "<<pointer_position;
       }
     }
     fclose(outfile);
     return pointer_position;
   }
static long rwLASMParameters (FILE * outfile, const char * file_path, const char * mode, config::lasm lasm_parameters[], int iteration, int number_of_rounds, long ptr_position) inline static
Read or write Logistic Adjusted Sine Map parameters.
Takes Logistic Adjusted Sine Map parameters, filepath, iteration and number of rounds as arguments
Offset pointer position by length of previous record
Write LASM parameters to file
Update pointer position after writing
Offset pointer position by length of previous record
Read LASM parameters from file
Update pointer position after reading
Definition at line 309 of file io.hpp.
References DEBUG_READ_WRITE.
Referenced by pattern::rwMapParameters().
   {
     long pointer_position = ptr_position;
     int fwrite_status = 9,fseek_status = 9,fread_status = 9;
     outfile = fopen(file_path,mode);
     if(outfile == NULL)
     {
       cout<<"\nCould not open "<<file_path<<"\nExiting...";
       exit(0);
     }
     if(strcmp("wb",mode) == 0 || strcmp("ab",mode) == 0)
     {
       if(pointer_position > 0)
       {
          fseek_status = fseek(outfile,(pointer_position + 1),SEEK_SET);
          pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before writing lasm_parameters = "<<fseek_status;
         cout<<"\npointer position before writing lasm_parameters = "<<pointer_position;
       }
       size_t size = sizeof(lasm_parameters[0]) * number_of_rounds;
       fwrite_status = fwrite(lasm_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfwrite status after writing lasm_parameters = "<<fwrite_status;
         cout<<"\npointer position after writing lasm_parameters = "<<pointer_position;
       }
     }
     else
     {
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\npointer position before writing lasm_parameters = "<<pointer_position;
       }
       if(pointer_position > 0)
       {
          fseek_status = fseek(outfile,(pointer_position),SEEK_SET);
          pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before reading lasm_parameters = "<<fseek_status;
         cout<<"\npointer position before reading lasm_parameters = "<<pointer_position;
       }
       size_t size = sizeof(lasm_parameters[0]) * number_of_rounds;
       fread_status = fread(lasm_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfread status after reading lasm_parameters = "<<fread_status;
         cout<<"\npointer position after reading lasm_parameters = "<<pointer_position;
       }
     }
     fclose(outfile);
     return pointer_position;
   }
static long rwLALMParameters (FILE * outfile, const char * file_path, const char * mode, config::lalm lalm_parameters[], int iteration, int number_of_rounds, long ptr_position) inline static
Read or write Logistic Adjusted Logistic Map parameters.
Takes Logistic Adjusted Logistic Map parameters, filepath, iteration and number of rounds as arguments
Offset pointer position by length of previous record
Write LALM parameters to file
Update pointer position after writing
Offset pointer position by length of previous record
Read LALM parameters from file
Update pointer position after reading
Definition at line 406 of file io.hpp.
References DEBUG_READ_WRITE.
Referenced by pattern::rwMapParameters().
   {
     long pointer_position = ptr_position;
     int fwrite_status = 9,fseek_status = 9,fread_status = 9;
     outfile = fopen(file_path,mode);
     if(outfile == NULL)
     {
       cout<<"\nCould not open "<<file_path<<"\nExiting...";
       exit(0);
     }
     if(strcmp("wb",mode) == 0 || strcmp("ab",mode) == 0)
     {
       if(pointer_position > 0)
       {
          fseek_status = fseek(outfile,(pointer_position + 1),SEEK_SET);
          pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before writing lalm_parameters = "<<fseek_status;
         cout<<"\npointer position before writing lalm_parameters = "<<pointer_position;
       }
       size_t size = sizeof(lalm_parameters[0]) * number_of_rounds;
       fwrite_status = fwrite(lalm_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfwrite status after writing lalm_parameters = "<<fwrite_status;
         cout<<"\npointer position after writing lalm_parameters = "<<pointer_position;
       }
     }
     else
     {
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\npointer position before reading lalm_parameters  = "<<pointer_position;
       }
       if(pointer_position > 0)
       {
          fseek_status = fseek(outfile,(pointer_position),SEEK_SET);
          pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before reading lalm_parameters = "<<fseek_status;
         cout<<"\npointer position before reading lalm_parameters = "<<pointer_position;
       }
       size_t size = sizeof(lalm_parameters[0]) * number_of_rounds;
       fread_status = fread(lalm_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfread status after writing lalm_parameters = "<<fread_status;
         cout<<"\npointer position after reading lalm_parameters = "<<pointer_position;
       }
     }
     fclose(outfile);
     return pointer_position;
   }
static long rwMTParameters (FILE * outfile, const char * file_path, const char * mode, config::mt mt_parameters[], int iteration, int number_of_rounds, long ptr_position) inline static
Read or write Mersenne Twister seed.
Takes Mersenne Twister parameters, filepath, iteration and number of rounds as arguments
Offset pointer position by length of previous record
Write MT parameters to file
Update pointer position after writing
Offset pointer position by length of previous record
Write MT parameters to file
Update pointer position after writing
Definition at line 504 of file io.hpp.
References DEBUG_READ_WRITE.
Referenced by pattern::rwMapParameters().
   {
     int fseek_status = 9,fwrite_status = 9,fread_status = 9;
     long pointer_position = ptr_position;
     outfile = fopen(file_path,mode);
     if(outfile == NULL)
     {
       cout<<"\nCould not open "<<file_path<<"\nExiting...";
       exit(0);
     }
     if(strcmp("wb",mode) == 0 || strcmp("ab",mode) == 0)
     {
       if(pointer_position > 0)
       {
         fseek_status = fseek(outfile,(pointer_position + 1),SEEK_SET);
         pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before writing basic parameters = "<<fseek_status;
         cout<<"\npointer position before writing basic parameters = "<<pointer_position;
       }
       size_t size = sizeof(mt_parameters[0]) * number_of_rounds;
       fwrite_status = fwrite(mt_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfwrite status after writing basic parameters = "<<fwrite_status;
         cout<<"\npointer position after writing basic parameters = "<<pointer_position;
       }
     }
     else
     {
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\npointer position before reading mt_parameters = "<<pointer_position;
       }
       if(pointer_position > 0)
       {
         fseek_status = fseek(outfile,(pointer_position),SEEK_SET);
         pointer_position = ftell(outfile);
       }
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\n\niteration = "<<iteration;
         cout<<"\nfseek status before reading basic parameters = "<<fseek_status;
         cout<<"\npointer position before reading basic parameters = "<<pointer_position;
       }
       size_t size = sizeof(mt_parameters[0]) * number_of_rounds;
       fread_status = fread(mt_parameters,size,1,outfile);
       pointer_position = ftell(outfile);
       if(DEBUG_READ_WRITE == 1)
       {
         cout<<"\nfread status after reading basic parameters = "<<fread_status;
         cout<<"\npointer position after reading basic parameters = "<<pointer_position;
       }
     }
     fclose(outfile);
     return pointer_position;
   }