CUDA-Image-Encryption: config Namespace Reference
config Namespace Reference
Classes
struct lalm
Structure to store Logistic Adjusted Logistic Map parameters.
struct lasm
Structure to store Logistic Adjusted Sine Map parameters.
struct lm
Structure to store Logistic Map parameters.
struct lma
Structure to store Advanced Logistic Map parameters.
struct mt
Structure to store Mersenne Twister parameters.
struct slmm
Structure to store Sine Logistic Modulation Map parameters.
Enumerations
enum ChaoticMap {
ChaoticMap::TwoDLogisticMap = 1, ChaoticMap::TwoDLogisticMapAdvanced, ChaoticMap::TwoDLogisticAdjustedSineMap, ChaoticMap::TwoDSineLogisticModulationMap,
ChaoticMap::TwoDLogisticAdjustedLogisticMap
}
Enumeration class used to denote Chaotic Map choices.
Variables
int lower_limit = 1
Range of pseudorandom values to be produced by Mersenne Twister.
int upper_limit = (rows * cols * 3) + 1
std::string parameters_file = "parameters"
The file path of the parameter file where all parameters are stored.
std::string binary_extension = ".bin"
std::string parameters_file_path = parameters_file + binary_extension
char * constant_parameters_file_path = const_cast<char*>(parameters_file_path.c_str())
char* constant strings for use with standard C file handling functions
Enumeration Type Documentation
enum config::ChaoticMap strong
Enumeration class used to denote Chaotic Map choices.
Enumerator
TwoDLogisticMap
TwoDLogisticMapAdvanced
TwoDLogisticAdjustedSineMap
TwoDSineLogisticModulationMap
TwoDLogisticAdjustedLogisticMap
Definition at line 105 of file config.hpp.
   {
     TwoDLogisticMap = 1,
     TwoDLogisticMapAdvanced,
     TwoDLogisticAdjustedSineMap,
     TwoDSineLogisticModulationMap,
     TwoDLogisticAdjustedLogisticMap
   };
Variable Documentation
int config::lower_limit = 1
Range of pseudorandom values to be produced by Mersenne Twister.
Definition at line 99 of file config.hpp.
Referenced by pattern::selectChaoticMap().
int config::upper_limit = (rows * cols * 3) + 1
Definition at line 100 of file config.hpp.
Referenced by pattern::selectChaoticMap().
std::string config::parameters_file = "parameters"
The file path of the parameter file where all parameters are stored.
Definition at line 184 of file config.hpp.
std::string config::binary_extension = ".bin"
Definition at line 185 of file config.hpp.
std::string config::parameters_file_path = parameters_file + binary_extension
Definition at line 186 of file config.hpp.
char* config::constant_parameters_file_path = const_cast<char*>(parameters_file_path.c_str())
char* constant strings for use with standard C file handling functions
Definition at line 191 of file config.hpp.
Referenced by main(), and pattern::rwMapParameters().